name: medico_lavoro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  go_router: ^14.2.8
  google_fonts: ^6.1.0
  responsive_framework: ^1.5.1
  cupertino_icons: ^1.0.2
  google_static_maps_controller: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
